apiVersion: v1
kind: ServiceAccount
metadata:
  name: gaudi3-scale
  namespace: gaudi3-scale
  labels:
    app.kubernetes.io/name: gaudi3-scale
    app.kubernetes.io/component: serviceaccount
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gaudi3-scale-role
  namespace: gaudi3-scale
  labels:
    app.kubernetes.io/name: gaudi3-scale
    app.kubernetes.io/component: rbac
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gaudi3-scale-rolebinding
  namespace: gaudi3-scale
  labels:
    app.kubernetes.io/name: gaudi3-scale
    app.kubernetes.io/component: rbac
subjects:
- kind: ServiceAccount
  name: gaudi3-scale
  namespace: gaudi3-scale
roleRef:
  kind: Role
  name: gaudi3-scale-role
  apiGroup: rbac.authorization.k8s.io