global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'gaudi-trainer'
    static_configs:
      - targets: ['gaudi-trainer:8000']
    scrape_interval: 10s
    metrics_path: '/metrics'
  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: 'habana-exporter'
    static_configs:
      - targets: ['gaudi-trainer:9200']
    scrape_interval: 5s
    metrics_path: '/hpu-metrics'