name: 🔒 Security Vulnerability
description: Report a security vulnerability (use private reporting for critical issues)
title: "[SECURITY] "
labels: ["security", "vulnerability", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Security Vulnerability Reporting
        
        **For critical security vulnerabilities, please use [Private Security Reporting](../../security/advisories/new) instead of public issues.**
        
        This template is for non-critical security improvements and general security-related discussions.

  - type: checkboxes
    id: severity_check
    attributes:
      label: Severity Assessment
      description: Please confirm this is appropriate for public reporting
      options:
        - label: This is NOT a critical vulnerability requiring private disclosure
          required: true
        - label: I have reviewed the security policy in SECURITY.md
          required: true
        - label: I understand that critical vulnerabilities should be reported privately
          required: true

  - type: dropdown
    id: vulnerability_type
    attributes:
      label: Vulnerability Type
      description: What type of security issue is this?
      options:
        - Dependency vulnerability (non-critical)
        - Configuration security improvement
        - Code security hardening
        - Documentation security gap
        - Security tooling enhancement
        - Supply chain security
        - Container security improvement
        - Access control improvement
        - Other (non-critical)
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How would you rate this security issue?
      options:
        - Low (security hardening, best practices)
        - Medium (potential security improvement)
        - High (should be reported privately)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the security concern or improvement
      placeholder: |
        **Security Issue:**
        Brief description of the security concern or area for improvement.
        
        **Impact:**
        What could happen if this isn't addressed?
        
        **Context:**
        Where does this occur in the codebase or infrastructure?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Affected Environment
      description: Where does this security issue apply?
      placeholder: |
        - Component: Training pipeline / Infrastructure / Documentation
        - Version: 0.1.0
        - Environment: Development / Staging / Production
        - Scope: Local / Container / Cloud deployment
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce (if applicable)
      description: How can we reproduce or verify this security concern?
      placeholder: |
        1. Set up environment...
        2. Run specific command or configuration...
        3. Observe security concern...
        
        Note: Do not include actual exploit code or sensitive details.
    validations:
      required: false

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: Do you have suggestions for addressing this security concern?
      placeholder: |
        **Suggested approaches:**
        - Update dependency to version X.Y.Z
        - Modify configuration to use secure defaults
        - Add security validation in component X
        - Improve documentation section Y
        
        **Security best practices:**
        - Reference to security standards or guidelines
        - Industry best practices to follow
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: |
        **References:**
        - Links to security advisories
        - Industry security guidelines
        - Similar issues in other projects
        
        **Security tools:**
        - Output from security scanners
        - Static analysis results
        - Dependency audit results
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Can you help address this security concern?
      options:
        - label: I can submit a pull request with a fix
        - label: I can help test security improvements
        - label: I can provide additional security research
        - label: I can help with security documentation

  - type: markdown
    attributes:
      value: |
        ## 📋 Security Response Process
        
        1. **Triage**: Security team will assess and prioritize
        2. **Investigation**: Technical analysis and impact assessment
        3. **Resolution**: Implement fix or security improvement
        4. **Verification**: Test security enhancement
        5. **Disclosure**: Update security documentation and notify if needed
        
        For urgent security issues, please contact: security@gaudi3-scale.org