version: '3.8'

services:
  gaudi3-scale:
    build: .
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - OPTIMIZATION_LEVEL=extreme
      - CACHE_SIZE=2000
      - MAX_WORKERS=8
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: unless-stopped

volumes:
  redis_data:
  prometheus_data:
